# ================================
# Build image
# ================================
FROM swift:6.1.0-noble AS build

# Install OS updates
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y \
    && apt-get install -y libjemalloc-dev

# Set up a build area
WORKDIR /staging

# Copy entire repo into container
COPY . .

RUN pwd && ls -lA && swift build -c release --show-bin-path && ls -lA $(swift build -c release --show-bin-path)

# Copy main executable to staging area
RUN cp "$(swift build -c release --show-bin-path)/App" ./

# Copy static swift backtracer binary to staging area
RUN cp "/usr/libexec/swift/linux/swift-backtrace-static" ./

# Copy resources bundled by SPM to staging area
RUN find -L "$(swift build -c release --show-bin-path)/" -regex '.*\.resources$' -exec cp -Ra {} ./ \;

# Copy any resources from the public directory and views directory if the directories exist
# Ensure that by default, neither the directory nor any of its contents are writable.
RUN [ -d /build/Public ] && { chmod -R a-w ./Public; } || true
RUN [ -d /build/Resources ] && { chmod -R a-w ./Resources; } || true

ENTRYPOINT ["./App"]
